<script>
    import { connected, signerAddress } from 'svelte-wagmi'
    import { onMount } from 'svelte'
    import { walletOfOwner, isApprovedForAll, setApprovalForAll } from '$lib/contracts/nft'
    import { stake, userStakeInfo, withdraw, claimRewards } from '$lib/contracts/nftStaking'
    import { config, contracts } from '$lib/config'
    import { NotConnected } from '$lib/components'
    import { ethers } from 'ethers'

    let nfts = []
    let rewards
    let approved = false
    let info
    let staked = []

    const updateOwnedNFTs = async() => {
        let owned = await walletOfOwner($signerAddress)
        if (owned) {
            nfts = owned
        } else {
            nfts = []
        }
        nfts = nfts
    }

    const updateStakedInfo = async () => {
        let userInfo = await userStakeInfo($signerAddress)

        if (userInfo[0].length > 0) {
            userInfo[0].forEach((stakedId) => {
                staked.push(Number(stakedId))
            })
        } else {
            staked = []
        }
        staked = staked

        if (userInfo[1]) {
            rewards = ethers.utils.formatEther(userInfo[1])
        }
    }

    const updateIsApproved = async() => {
        approved = await isApprovedForAll($signerAddress, contracts.nftStaking.address)
    }

    const onApproveClick = async() => {
        await setApprovalForAll(contracts.nftStaking.address, true)
        updateIsApproved()
    }

    const onStakeClick = async(tokenIds) => {
        await stake(tokenIds)
        updateOwnedNFTs()
        updateStakedInfo()
    }

    const onUnstakeClick = async(tokenIds) => {
        await withdraw(tokenIds)
        updateOwnedNFTs()
        updateStakedInfo()
    }

    const onClaimClick = async() => {
        await claimRewards()
        updateStakedInfo()
    }

    onMount(async () => {
        updateOwnedNFTs()
        updateIsApproved()
        updateStakedInfo()
    })

    
</script>

<svelte:head>
    <title>The Grid - CyberLock</title>
</svelte:head>

<div class="pixelFont text-xs md:text-sm bg-[#0e0f14] w-full rounded-lg p-6 md:p-12 mb-6 border-green-500 border">
    <p>
        You approach the <strong>CyberLock</strong>, an imposing vault that represents
         the heart of The Grid's staking system. You place your NFT character on the pedestal, 
         and the holographic display starts to pulse with energy. As your character is secured 
         within the CyberLock, you watch the GRID being generated by your staked character, 
         a testament to the value of your investment in The Grid.
    </p>
    <p class="mt-6">
        With your NFT character securely staked, you're free
         to explore the world of The Grid, confident in the knowledge that your investment
          is working for you. So come and join us at the CyberLock staking page, and start earning GRID today. 
          The future of The Grid is waiting for you.
    </p>
</div>

{#if !$connected}
    <NotConnected />
{:else}

{#if rewards}
<div class="pixelFont text-xs md:text-sm bg-[#0e0f14] rounded-lg p-12 mb-6">
    <h2 class="text-xl mb-8">Earnings</h2>
    <h3 class="text-2xl text-green-500">{rewards} $GRID</h3>
    <button on:click={onClaimClick} class="btn btn-primary text-xs bg-green-500 border-none hover:bg-pink-500 w-32 mt-6">Claim</button>
</div>
{/if}

<div class="pixelFont text-xs md:text-sm bg-[#0e0f14] rounded-lg p-12">
    <h2 class="text-xl mb-8">Staked</h2>
    {#if staked.length > 1}
    <button on:click={() => onUnstakeClick(staked)} class="btn btn-secondary border-none bg-green-500 hover:bg-pink-600 mb-4" disabled={!approved}>Unstake All ({staked.length})</button>
    {/if}
    {#if staked.length > 0}
    <div class="grid grid-cols-1 md:grid-cols-5 gap-2">
        {#each staked as nft}
            <div class="card card-compact w-64 bg-base-100 hover:border-4 border-pink-500">
                <figure><img src="{config.imageBase}{nft}.png" alt="NFT" /></figure>
                <div class="card-body">
                  <div class="card-actions">
                    <button on:click={() => onUnstakeClick(nft)} class="btn btn-primary text-xs bg-green-500 border-none hover:bg-pink-500 w-full hover:animate-pulse" disabled={!approved}>Unstake</button>
                  </div>
                </div>
            </div>
        {/each}
    </div>
    {/if}
</div>

<div class="pixelFont text-xs md:text-sm bg-[#0e0f14] rounded-lg p-12 mt-6">
    <h2 class="text-xl mb-4">Inventory</h2>
    {#if !approved}
    <button on:click={onApproveClick} class="btn btn-secondary border-none bg-green-500 hover:bg-pink-600 mb-4">Approve</button>
    {/if}
    {#if nfts.length > 1}
    <button on:click={() => onStakeClick(nfts)} class="btn btn-secondary border-none bg-green-500 hover:bg-pink-600 mb-4" disabled={!approved}>Stake All ({nfts.length})</button>
    {/if}
    {#if nfts.length > 0}
    <div class="grid grid-cols-1 md:grid-cols-5 gap-2">
        {#each nfts as nft}
            <div class="card card-compact w-64 bg-base-100 hover:border-4 border-pink-500">
                <figure><img src="{config.imageBase}{nft}.png" alt="NFT" /></figure>
                <div class="card-body">
                  <div class="card-actions">
                    <button on:click={() => onStakeClick(nft)} class="btn btn-primary text-xs bg-green-500 border-none hover:bg-pink-500 w-full hover:animate-pulse" disabled={!approved}>Stake</button>
                  </div>
                </div>
            </div>
        {/each}
    </div>
    {/if}
</div>

{/if}